// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Validate environment variables
if (!SUPABASE_URL) {
  console.error('❌ Missing VITE_SUPABASE_URL environment variable');
  console.error('Please add it to your .env file: VITE_SUPABASE_URL=https://your-project.supabase.co');
}

if (!SUPABASE_PUBLISHABLE_KEY) {
  console.error('❌ Missing VITE_SUPABASE_PUBLISHABLE_KEY environment variable');
  console.error('Please add it to your .env file: VITE_SUPABASE_PUBLISHABLE_KEY=your-anon-key');
}

if (SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY) {
  console.log('✅ Supabase client initialized');
  console.log('📍 URL:', SUPABASE_URL);
} else {
  console.warn('⚠️ Supabase client initialized with missing credentials');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL || 'https://placeholder.supabase.co',
  SUPABASE_PUBLISHABLE_KEY || 'placeholder-key',
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);